import type { User, Content, Task, ScheduleEntry, Message, AIInteraction, TokenBalance, QuizScore, LearningGoal } from './types'

// Mock Users
export const mockStudentUser: User = {
  id: 'usr_student_001',
  email: 'john.kamara@student.lusl.edu.sl',
  full_name: 'John Kamara',
  role: 'student',
  user_type: 'student',
  faculty: 'FICT',
  semester: 3,
  program: 'BIT',
  student_id: '905001234',
  avatar_url: '',
  terms_accepted: true,
  referral_code: 'JOHN1234',
  created_at: '2025-09-01T00:00:00Z',
}

export const mockLecturerUser: User = {
  id: 'usr_lecturer_001',
  email: 'dr.williams@lusl.edu.sl',
  full_name: 'Dr. Sarah Williams',
  role: 'lecturer',
  user_type: 'lecturer',
  faculty: 'FICT',
  avatar_url: '',
  terms_accepted: true,
  referral_code: 'SARAH001',
  created_at: '2025-01-15T00:00:00Z',
}

export const mockAdminUser: User = {
  id: 'usr_admin_001',
  email: 'admin@lusl.edu.sl',
  full_name: 'System Administrator',
  role: 'admin',
  user_type: 'admin',
  avatar_url: '',
  terms_accepted: true,
  referral_code: 'ADMIN001',
  created_at: '2024-12-01T00:00:00Z',
}

// Mock Content
export const mockContents: Content[] = [
  {
    id: 'cnt_001',
    title: 'Introduction to Database Management Systems',
    description: 'Comprehensive introduction to DBMS concepts, including relational databases, SQL, and normalization.',
    file_url: '/files/dbms-intro.pdf',
    file_type: 'pdf',
    faculty: 'FICT',
    semester: 3,
    program: 'BIT',
    module: 'Database Systems',
    module_id: 'mod_3',
    module_code: 'FICT301',
    content_type: 'lecture_notes',
    lecturer_name: 'Dr. Sarah Williams',
    lecturer_id: 'usr_lecturer_001',
    view_count: 245,
    download_count: 89,
    is_active: true,
    status: 'active',
    created_at: '2026-02-15T10:00:00Z',
    updated_at: '2026-02-15T10:00:00Z',
  },
  {
    id: 'cnt_002',
    title: 'Object-Oriented Programming with Java',
    description: 'Learn the fundamentals of OOP using Java programming language.',
    file_url: '/files/oop-java.pptx',
    file_type: 'pptx',
    faculty: 'FICT',
    semester: 3,
    program: 'BIT',
    module: 'Programming II',
    module_id: 'mod_1',
    module_code: 'FICT302',
    content_type: 'lecture_notes',
    lecturer_name: 'Mr. Ibrahim Conteh',
    lecturer_id: 'usr_lecturer_002',
    view_count: 312,
    download_count: 156,
    is_active: true,
    status: 'active',
    created_at: '2026-02-10T14:30:00Z',
    updated_at: '2026-02-10T14:30:00Z',
  },
  {
    id: 'cnt_003',
    title: 'Web Development Assignment 1',
    description: 'Build a responsive portfolio website using HTML, CSS, and JavaScript.',
    file_url: '/files/web-assignment-1.pdf',
    file_type: 'pdf',
    faculty: 'FICT',
    semester: 3,
    program: 'BIT',
    module: 'Web Development',
    module_id: 'mod_1',
    module_code: 'FICT303',
    content_type: 'assignment',
    lecturer_name: 'Dr. Sarah Williams',
    lecturer_id: 'usr_lecturer_001',
    view_count: 178,
    download_count: 145,
    is_active: true,
    status: 'active',
    created_at: '2026-02-20T09:00:00Z',
    updated_at: '2026-02-20T09:00:00Z',
  },
  {
    id: 'cnt_004',
    title: 'Data Structures and Algorithms',
    description: 'Arrays, linked lists, stacks, queues, trees, and graph algorithms.',
    file_url: '/files/dsa-notes.docx',
    file_type: 'docx',
    faculty: 'FICT',
    semester: 3,
    program: 'BIT',
    module: 'Data Structures',
    module_id: 'mod_2',
    module_code: 'FICT304',
    content_type: 'lecture_notes',
    lecturer_name: 'Prof. David Bangura',
    lecturer_id: 'usr_lecturer_003',
    view_count: 421,
    download_count: 287,
    is_active: true,
    status: 'active',
    created_at: '2026-01-28T11:00:00Z',
    updated_at: '2026-01-28T11:00:00Z',
  },
  {
    id: 'cnt_005',
    title: 'Network Security Fundamentals',
    description: 'Introduction to cybersecurity concepts, encryption, and secure protocols.',
    file_url: '/files/network-security.pdf',
    file_type: 'pdf',
    faculty: 'FICT',
    semester: 3,
    program: 'BIT',
    module: 'Computer Networks',
    module_id: 'mod_1',
    module_code: 'FICT305',
    content_type: 'lecture_notes',
    lecturer_name: 'Mr. Joseph Koroma',
    lecturer_id: 'usr_lecturer_004',
    view_count: 198,
    download_count: 112,
    is_active: true,
    status: 'active',
    created_at: '2026-02-05T16:00:00Z',
    updated_at: '2026-02-05T16:00:00Z',
  },
  {
    id: 'cnt_006',
    title: 'Semester 3 Timetable - FICT',
    description: 'Official class schedule for FICT Semester 3 students.',
    file_url: '/files/fict-timetable.pdf',
    file_type: 'pdf',
    faculty: 'FICT',
    semester: 3,
    program: 'BIT',
    module: 'General',
    module_id: 'mod_1',
    module_code: 'FICT000',
    content_type: 'timetable',
    lecturer_name: 'Faculty Office',
    lecturer_id: 'usr_admin_001',
    view_count: 567,
    download_count: 423,
    is_active: true,
    status: 'active',
    created_at: '2026-01-15T08:00:00Z',
    updated_at: '2026-01-15T08:00:00Z',
  },
]

// Mock Tasks
export const mockTasks: Task[] = [
  {
    id: 'task_001',
    user_id: 'usr_student_001',
    title: 'Complete Database Assignment',
    description: 'Design and implement a library management system database',
    deadline: '2026-03-30T23:59:00Z',
    priority: 'high',
    status: 'in_progress',
    tags: ['Database', 'Assignment'],
    collaborators: [],
    created_at: '2026-03-20T10:00:00Z',
    updated_at: '2026-03-20T10:00:00Z',
  },
  {
    id: 'task_002',
    user_id: 'usr_student_001',
    title: 'Study for Programming Exam',
    description: 'Review OOP concepts, inheritance, polymorphism',
    deadline: '2026-04-05T09:00:00Z',
    priority: 'high',
    status: 'pending',
    tags: ['Exam', 'Programming'],
    collaborators: [],
    created_at: '2026-03-18T14:00:00Z',
    updated_at: '2026-03-18T14:00:00Z',
  },
  {
    id: 'task_003',
    user_id: 'usr_student_001',
    title: 'Web Development Project',
    description: 'Build portfolio website with responsive design',
    deadline: '2026-04-10T17:00:00Z',
    priority: 'medium',
    status: 'pending',
    tags: ['Web', 'Project'],
    collaborators: ['mary.sesay@student.lusl.edu.sl'],
    created_at: '2026-03-15T09:00:00Z',
    updated_at: '2026-03-15T09:00:00Z',
  },
  {
    id: 'task_004',
    user_id: 'usr_student_001',
    title: 'Read Network Security Chapter 5',
    description: 'Encryption algorithms and SSL/TLS protocols',
    deadline: '2026-03-28T18:00:00Z',
    priority: 'low',
    status: 'completed',
    tags: ['Reading', 'Security'],
    collaborators: [],
    created_at: '2026-03-10T11:00:00Z',
    updated_at: '2026-03-25T16:00:00Z',
  },
]

// Mock Schedule Entries
export const mockScheduleEntries: ScheduleEntry[] = [
  {
    id: 'sch_001',
    user_id: 'usr_student_001',
    day: 'monday',
    start_time: '08:00',
    end_time: '10:00',
    subject: 'Database Systems',
    location: 'Room 201',
    type: 'lecture',
    created_at: '2026-01-15T00:00:00Z',
  },
  {
    id: 'sch_002',
    user_id: 'usr_student_001',
    day: 'monday',
    start_time: '10:30',
    end_time: '12:30',
    subject: 'Programming II',
    location: 'Lab 3',
    type: 'lab',
    created_at: '2026-01-15T00:00:00Z',
  },
  {
    id: 'sch_003',
    user_id: 'usr_student_001',
    day: 'tuesday',
    start_time: '09:00',
    end_time: '11:00',
    subject: 'Web Development',
    location: 'Room 105',
    type: 'lecture',
    created_at: '2026-01-15T00:00:00Z',
  },
  {
    id: 'sch_004',
    user_id: 'usr_student_001',
    day: 'tuesday',
    start_time: '14:00',
    end_time: '16:00',
    subject: 'Data Structures',
    location: 'Room 301',
    type: 'lecture',
    created_at: '2026-01-15T00:00:00Z',
  },
  {
    id: 'sch_005',
    user_id: 'usr_student_001',
    day: 'wednesday',
    start_time: '08:00',
    end_time: '10:00',
    subject: 'Computer Networks',
    location: 'Room 202',
    type: 'lecture',
    created_at: '2026-01-15T00:00:00Z',
  },
  {
    id: 'sch_006',
    user_id: 'usr_student_001',
    day: 'thursday',
    start_time: '10:00',
    end_time: '12:00',
    subject: 'Database Systems',
    location: 'Lab 2',
    type: 'tutorial',
    created_at: '2026-01-15T00:00:00Z',
  },
  {
    id: 'sch_007',
    user_id: 'usr_student_001',
    day: 'friday',
    start_time: '09:00',
    end_time: '11:00',
    subject: 'Web Development',
    location: 'Lab 1',
    type: 'lab',
    created_at: '2026-01-15T00:00:00Z',
  },
]

// Mock Messages
export const mockMessages: Message[] = [
  {
    id: 'msg_001',
    sender_id: 'usr_lecturer_001',
    sender_name: 'Dr. Sarah Williams',
    recipient_id: 'usr_student_001',
    recipient_email: 'john.kamara@student.lusl.edu.sl',
    subject: 'Assignment Deadline Extension',
    body: 'Dear John,\n\nI am writing to inform you that the deadline for the Database Assignment has been extended to March 30th. Please ensure you submit your work on time.\n\nBest regards,\nDr. Williams',
    is_read: false,
    created_at: '2026-03-25T14:30:00Z',
  },
  {
    id: 'msg_002',
    sender_id: 'usr_admin_001',
    sender_name: 'System Administrator',
    recipient_id: 'usr_student_001',
    recipient_email: 'john.kamara@student.lusl.edu.sl',
    subject: 'Welcome to LUSL Notepad',
    body: 'Welcome to LUSL Notepad! Your account has been successfully created. You now have access to all course materials for your faculty and semester.\n\nIf you have any questions, please contact support.',
    is_read: true,
    created_at: '2026-01-10T09:00:00Z',
  },
  {
    id: 'msg_003',
    sender_id: 'usr_lecturer_002',
    sender_name: 'Mr. Ibrahim Conteh',
    recipient_id: 'usr_student_001',
    recipient_email: 'john.kamara@student.lusl.edu.sl',
    subject: 'Programming Exam Schedule',
    body: 'Dear Students,\n\nThe Programming II exam has been scheduled for April 5th at 9:00 AM in Room 301. Please come prepared with your student ID.\n\nGood luck with your studies!',
    is_read: true,
    created_at: '2026-03-20T11:00:00Z',
  },
]

// Mock AI Interactions
export const mockAIInteractions: AIInteraction[] = [
  {
    id: 'ai_001',
    user_id: 'usr_student_001',
    query: 'Explain the concept of database normalization',
    response: 'Database normalization is the process of organizing data in a database to reduce redundancy and improve data integrity...',
    source_content_ids: ['cnt_001'],
    query_type: 'chat',
    satisfaction_rating: 5,
    response_time: 2500,
    created_at: '2026-03-26T10:30:00Z',
  },
  {
    id: 'ai_002',
    user_id: 'usr_student_001',
    query: 'Generate a study guide for OOP concepts',
    response: '# Object-Oriented Programming Study Guide\n\n## 1. Core Concepts\n- Classes and Objects\n- Encapsulation\n- Inheritance\n- Polymorphism...',
    source_content_ids: ['cnt_002'],
    query_type: 'study_guide',
    satisfaction_rating: 4,
    response_time: 5200,
    created_at: '2026-03-25T15:00:00Z',
  },
]

// Mock Token Balance
export const mockTokenBalance: TokenBalance = {
  id: 'bal_001',
  user_id: 'usr_student_001',
  available: 35,
  used: 15,
  total: 50,
  bonus: 5,
}

// Mock Quiz Scores
export const mockQuizScores: QuizScore[] = [
  {
    id: 'quiz_001',
    user_id: 'usr_student_001',
    module: 'Database Systems',
    quiz_type: 'practice_quiz',
    score: 8,
    total_questions: 10,
    percentage: 80,
    created_at: '2026-03-24T16:00:00Z',
  },
  {
    id: 'quiz_002',
    user_id: 'usr_student_001',
    module: 'Programming II',
    quiz_type: 'true_false',
    score: 10,
    total_questions: 12,
    percentage: 83,
    created_at: '2026-03-22T14:30:00Z',
  },
  {
    id: 'quiz_003',
    user_id: 'usr_student_001',
    module: 'Data Structures',
    quiz_type: 'practice_quiz',
    score: 6,
    total_questions: 10,
    percentage: 60,
    created_at: '2026-03-20T11:00:00Z',
  },
  {
    id: 'quiz_004',
    user_id: 'usr_student_001',
    module: 'Web Development',
    quiz_type: 'fill_blanks',
    score: 9,
    total_questions: 10,
    percentage: 90,
    created_at: '2026-03-18T09:00:00Z',
  },
]

// Mock Learning Goals
export const mockLearningGoals: LearningGoal[] = [
  {
    id: 'goal_001',
    user_id: 'usr_student_001',
    title: 'Master SQL Queries',
    description: 'Learn advanced SQL including joins, subqueries, and stored procedures',
    target_date: '2026-04-15',
    status: 'active',
    progress: 65,
    created_at: '2026-02-01T00:00:00Z',
    updated_at: '2026-03-20T00:00:00Z',
  },
  {
    id: 'goal_002',
    user_id: 'usr_student_001',
    title: 'Build 3 Web Projects',
    description: 'Complete three full-stack web development projects',
    target_date: '2026-05-30',
    status: 'active',
    progress: 33,
    created_at: '2026-01-15T00:00:00Z',
    updated_at: '2026-03-15T00:00:00Z',
  },
  {
    id: 'goal_003',
    user_id: 'usr_student_001',
    title: 'Learn Data Structures',
    description: 'Understand and implement common data structures',
    target_date: '2026-04-01',
    status: 'completed',
    progress: 100,
    created_at: '2026-01-10T00:00:00Z',
    updated_at: '2026-03-25T00:00:00Z',
  },
]

// All Mock Users for Admin
export const mockAllUsers: User[] = [
  mockStudentUser,
  mockLecturerUser,
  mockAdminUser,
  {
    id: 'usr_student_002',
    email: 'mary.sesay@student.lusl.edu.sl',
    full_name: 'Mary Sesay',
    role: 'student',
    user_type: 'student',
    faculty: 'FICT',
    semester: 3,
    program: 'BCS',
    student_id: '905002345',
    avatar_url: '',
    terms_accepted: true,
    referral_code: 'MARY2345',
    created_at: '2025-09-05T00:00:00Z',
  },
  {
    id: 'usr_student_003',
    email: 'abdul.bangura@student.lusl.edu.sl',
    full_name: 'Abdul Bangura',
    role: 'student',
    user_type: 'student',
    faculty: 'FCMB',
    semester: 2,
    program: 'BMC',
    student_id: '905003456',
    avatar_url: '',
    terms_accepted: true,
    referral_code: 'ABDUL456',
    created_at: '2025-09-10T00:00:00Z',
  },
  {
    id: 'usr_lecturer_002',
    email: 'ibrahim.conteh@lusl.edu.sl',
    full_name: 'Mr. Ibrahim Conteh',
    role: 'lecturer',
    user_type: 'lecturer',
    faculty: 'FICT',
    avatar_url: '',
    terms_accepted: true,
    referral_code: 'IBRA002',
    created_at: '2025-02-01T00:00:00Z',
  },
]

// Mock Modules for lectures
export const mockModules = [
  { id: 'mod_1', code: 'CS101', name: 'Introduction to Programming' },
  { id: 'mod_2', code: 'CS201', name: 'Data Structures' },
  { id: 'mod_3', code: 'CS301', name: 'Database Systems' },
  { id: 'mod_4', code: 'ENG101', name: 'English Composition' },
  { id: 'mod_5', code: 'MATH101', name: 'Calculus I' },
]

// Mock Faculties (alternative to constants)
export const mockFaculties = [
  {
    code: 'FICT',
    name: 'Faculty of Information & Communication Technology',
    programs: [
      { code: 'BIT', name: 'Bachelor of Information Technology' },
      { code: 'BCS', name: 'Bachelor of Computer Science' },
    ],
  },
  {
    code: 'FCMB',
    name: 'Faculty of Communication, Media & Broadcasting',
    programs: [
      { code: 'BMC', name: 'Bachelor of Mass Communication' },
      { code: 'BPR', name: 'Bachelor of Public Relations' },
    ],
  },
]
